version: '3'

services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - node
    networks:
      - node-network

  node:
    build:
      context: ./node
    container_name: node
    restart: always
    depends_on:
      - db
    networks:
      - node-network

  db:
    build:
      context: ./mysql
    container_name: db
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge