name: ci-golang-workflow
on: [ push ]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: cd continous-integration && go test
      - run: cd continous-integration && go run math.go
